### ISSUE TITLE
Add ZwiiCMS

### ISSUE THREAD

**Issue by nibreh** [ahadb/flat-file-cms#22]
A great french flat-file-CMS

http://zwiicms.com/
https://github.com/remijean/ZwiiCMS/

**Comment by yckart** [comment]
:+1:

**Comment by remijean** [comment]
:+1: :+1:

**Comment by ahadb** [comment]
Looks good, will add it in soon. Thanks :sparkles: :star2: :turtle:

**Comment by remijean** [comment]
Thanks you ! :smile:
