### ISSUE TITLE
typo in respository description

### ISSUE THREAD

**Issue by maybegeek** [ahadb/flat-file-cms#27]
in the respository description is the character 'r' missing:

* A list of __stictly__ flat-file cms systems

should be

* A list of __strictly__ flat-file cms systems

the 's' in cms stands for system, but I'm not a native speaker, just saying and being thankful for your list!

**Comment by ahadb** [comment]
Thank you.

**Comment by maybegeek** [comment]
thanks, fixed. I close the issue.
