### ISSUE TITLE
PmWiki

### ISSUE THREAD

**Issue by 151617** [ahadb/flat-file-cms#42]
Hello,

I guess PmWiki is flat file cms (for more than 10 years) ;
+has fastcache extension providing static pages, working fast
+has markdown markup extension for markdown syntax
+everything you need for serious or not serious work (search engine, upload, powerfull access rights, page lists, many variables for flexibility, versionning, etc.)
+have nothing you don't need (but you can add it). 

Although it is named "wiki" is was made first for cms purpose.

http://www.pmwiki.org/
http://www.pmwiki.org/wiki/Cookbook/FastCache
http://www.pmwiki.org/wiki/Cookbook/MarkdownMarkupExtension

Hope this helps contributing this usefull list : flat file cms is so good.

**Comment by ahadb** [comment]
does it connect to a db?

**Comment by Soeldner** [comment]
I dont think so. db is not mentioned in the installation instructions.
