### ISSUE TITLE
Add BoidCMS

### ISSUE THREAD

**Issue by shoaiyb** [ahadb/flat-file-cms#95]
Here is another tiny open-source flat-file CMS I just created.     

## BoidCMS
BoidCMS is a free and open-source flat file CMS for building simple websites and blogs in seconds, developed using PHP and uses JSON as a database.

**Technology:** PHP / JSON

**Templating:** HTML / PHP

**Formatting:** HTML

**Open source:** [yes](https://github.com/BoidCMS/BoidCMS)

**Website:** https://boidcms.github.io

**Comment by ahadb** [comment]
thanks, feel free to open a PR and add it.
